POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "firstname":"red",
    "lastname":"arrow",
    "email":"redarrow@gmail.com",
    "password":"password12345",
    "role":"HR"
}

###

POST http://localhost:5000/user/signin
Content-Type: application/json

{
    "username":"user123",
    "password":"password12345"
}